// Code generated by fastssz. DO NOT EDIT.
package eth

import (
	github_com_OffchainLabs_prysm_v7_consensus_types_primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the BatchSealPreimage object
func (b *BatchSealPreimage) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BatchSealPreimage object to a target array
func (b *BatchSealPreimage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint(dst, b.Slot)

	// Field (1) 'CommitteeIndex'
	dst = ssz.MarshalUint(dst, b.CommitteeIndex)

	// Field (2) 'Batcher'
	dst = ssz.MarshalUint(dst, b.Batcher)

	return
}

// UnmarshalSSZ ssz unmarshals the BatchSealPreimage object
func (b *BatchSealPreimage) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 24 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Slot](buf[0:8])

	// Field (1) 'CommitteeIndex'
	b.CommitteeIndex = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.CommitteeIndex](buf[8:16])

	// Field (2) 'Batcher'
	b.Batcher = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.ValidatorIndex](buf[16:24])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BatchSealPreimage object
func (b *BatchSealPreimage) SizeSSZ() (size int) {
	size = 24
	return
}

// HashTreeRoot ssz hashes the BatchSealPreimage object
func (b *BatchSealPreimage) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BatchSealPreimage object with a hasher
func (b *BatchSealPreimage) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	ssz.PutUint(hh, b.Slot)

	// Field (1) 'CommitteeIndex'
	ssz.PutUint(hh, b.CommitteeIndex)

	// Field (2) 'Batcher'
	ssz.PutUint(hh, b.Batcher)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BatcherPreimage object
func (b *BatcherPreimage) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BatcherPreimage object to a target array
func (b *BatcherPreimage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(52)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint(dst, b.Slot)

	// Field (1) 'CommitteeIndex'
	dst = ssz.MarshalUint(dst, b.CommitteeIndex)

	// Offset (2) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.AggregationBits)

	// Field (3) 'DataRoot'
	if size := len(b.DataRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.DataRoot", size, 32)
		return
	}
	dst = append(dst, b.DataRoot...)

	// Field (2) 'AggregationBits'
	if size := len(b.AggregationBits); size > 2048 {
		err = ssz.ErrBytesLengthFn("--.AggregationBits", size, 2048)
		return
	}
	dst = append(dst, b.AggregationBits...)

	return
}

// UnmarshalSSZ ssz unmarshals the BatcherPreimage object
func (b *BatcherPreimage) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 52 {
		return ssz.ErrSize
	}

	tail := buf
	var o2 uint64

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Slot](buf[0:8])

	// Field (1) 'CommitteeIndex'
	b.CommitteeIndex = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.CommitteeIndex](buf[8:16])

	// Offset (2) 'AggregationBits'
	if o2 = ssz.ReadOffset(buf[16:20]); o2 > size {
		return ssz.ErrOffset
	}

	if o2 != 52 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (3) 'DataRoot'
	if cap(b.DataRoot) == 0 {
		b.DataRoot = make([]byte, 0, len(buf[20:52]))
	}
	b.DataRoot = append(b.DataRoot, buf[20:52]...)

	// Field (2) 'AggregationBits'
	{
		buf = tail[o2:]
		if err = ssz.ValidateBitlist(buf, 2048); err != nil {
			return err
		}
		if cap(b.AggregationBits) == 0 {
			b.AggregationBits = make([]byte, 0, len(buf))
		}
		b.AggregationBits = append(b.AggregationBits, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BatcherPreimage object
func (b *BatcherPreimage) SizeSSZ() (size int) {
	size = 52

	// Field (2) 'AggregationBits'
	size += len(b.AggregationBits)

	return
}

// HashTreeRoot ssz hashes the BatcherPreimage object
func (b *BatcherPreimage) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BatcherPreimage object with a hasher
func (b *BatcherPreimage) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	ssz.PutUint(hh, b.Slot)

	// Field (1) 'CommitteeIndex'
	ssz.PutUint(hh, b.CommitteeIndex)

	// Field (2) 'AggregationBits'
	if len(b.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(b.AggregationBits, 2048)

	// Field (3) 'DataRoot'
	if size := len(b.DataRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.DataRoot", size, 32)
		return
	}
	hh.PutBytes(b.DataRoot)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BatchAttestation object
func (b *BatchAttestation) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BatchAttestation object to a target array
func (b *BatchAttestation) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(436)

	// Field (0) 'CommitteeIndex'
	dst = ssz.MarshalUint(dst, b.CommitteeIndex)

	// Offset (1) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.AggregationBits)

	// Field (2) 'Data'
	if b.Data == nil {
		b.Data = new(AttestationData)
	}
	if dst, err = b.Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'Signature'
	if size := len(b.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	dst = append(dst, b.Signature...)

	// Field (4) 'Batcher'
	dst = ssz.MarshalUint(dst, b.Batcher)

	// Field (5) 'BatchSeal'
	if size := len(b.BatchSeal); size != 96 {
		err = ssz.ErrBytesLengthFn("--.BatchSeal", size, 96)
		return
	}
	dst = append(dst, b.BatchSeal...)

	// Field (6) 'BatcherSignature'
	if size := len(b.BatcherSignature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.BatcherSignature", size, 96)
		return
	}
	dst = append(dst, b.BatcherSignature...)

	// Field (1) 'AggregationBits'
	if size := len(b.AggregationBits); size > 2048 {
		err = ssz.ErrBytesLengthFn("--.AggregationBits", size, 2048)
		return
	}
	dst = append(dst, b.AggregationBits...)

	return
}

// UnmarshalSSZ ssz unmarshals the BatchAttestation object
func (b *BatchAttestation) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 436 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'CommitteeIndex'
	b.CommitteeIndex = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.CommitteeIndex](buf[0:8])

	// Offset (1) 'AggregationBits'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 436 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (2) 'Data'
	if b.Data == nil {
		b.Data = new(AttestationData)
	}
	if err = b.Data.UnmarshalSSZ(buf[12:140]); err != nil {
		return err
	}

	// Field (3) 'Signature'
	if cap(b.Signature) == 0 {
		b.Signature = make([]byte, 0, len(buf[140:236]))
	}
	b.Signature = append(b.Signature, buf[140:236]...)

	// Field (4) 'Batcher'
	b.Batcher = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.ValidatorIndex](buf[236:244])

	// Field (5) 'BatchSeal'
	if cap(b.BatchSeal) == 0 {
		b.BatchSeal = make([]byte, 0, len(buf[244:340]))
	}
	b.BatchSeal = append(b.BatchSeal, buf[244:340]...)

	// Field (6) 'BatcherSignature'
	if cap(b.BatcherSignature) == 0 {
		b.BatcherSignature = make([]byte, 0, len(buf[340:436]))
	}
	b.BatcherSignature = append(b.BatcherSignature, buf[340:436]...)

	// Field (1) 'AggregationBits'
	{
		buf = tail[o1:]
		if err = ssz.ValidateBitlist(buf, 2048); err != nil {
			return err
		}
		if cap(b.AggregationBits) == 0 {
			b.AggregationBits = make([]byte, 0, len(buf))
		}
		b.AggregationBits = append(b.AggregationBits, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BatchAttestation object
func (b *BatchAttestation) SizeSSZ() (size int) {
	size = 436

	// Field (1) 'AggregationBits'
	size += len(b.AggregationBits)

	return
}

// HashTreeRoot ssz hashes the BatchAttestation object
func (b *BatchAttestation) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BatchAttestation object with a hasher
func (b *BatchAttestation) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'CommitteeIndex'
	ssz.PutUint(hh, b.CommitteeIndex)

	// Field (1) 'AggregationBits'
	if len(b.AggregationBits) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(b.AggregationBits, 2048)

	// Field (2) 'Data'
	if err = b.Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'Signature'
	if size := len(b.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	hh.PutBytes(b.Signature)

	// Field (4) 'Batcher'
	ssz.PutUint(hh, b.Batcher)

	// Field (5) 'BatchSeal'
	if size := len(b.BatchSeal); size != 96 {
		err = ssz.ErrBytesLengthFn("--.BatchSeal", size, 96)
		return
	}
	hh.PutBytes(b.BatchSeal)

	// Field (6) 'BatcherSignature'
	if size := len(b.BatcherSignature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.BatcherSignature", size, 96)
		return
	}
	hh.PutBytes(b.BatcherSignature)

	hh.Merkleize(indx)
	return
}
