syntax = "proto3";

package ethereum.eth.v1alpha1;

import "proto/prysm/v1alpha1/attestation.proto";
import "proto/prysm/v1alpha1/beacon_core_types.proto";
import "proto/engine/v1/execution_engine.proto";
import "proto/eth/ext/options.proto";
import "proto/prysm/v1alpha1/eip_7251.proto";

option csharp_namespace = "Ethereum.Eth.V1Alpha1";
option go_package = "github.com/OffchainLabs/prysm/v7/proto/prysm/v1alpha1;eth";
option java_multiple_files = true;
option java_outer_classname = "BeaconStateProto";
option java_package = "org.ethereum.eth.v1alpha1";
option php_namespace = "Ethereum\\Eth\\v1alpha1";

// ----------------------------------------------------------------------------
// Phase 0
// ----------------------------------------------------------------------------


message PendingAttestation {
  // Bitfield representation of validator indices that have voted exactly
  // the same vote and have been aggregated into this attestation.
  bytes aggregation_bits = 1 [
    (ethereum.eth.ext.ssz_max) = "2048",
    (ethereum.eth.ext.cast_type) = "github.com/OffchainLabs/go-bitfield.Bitlist"
  ];
  AttestationData data = 2;
  // The difference of when attestation gets created and get included on chain.
  uint64 inclusion_delay = 3 [
    (ethereum.eth.ext.cast_type) =
        "github.com/OffchainLabs/prysm/v7/consensus-types/primitives.Slot"
  ];
  // The proposer who included the attestation in the block.
  uint64 proposer_index = 4 [ (ethereum.eth.ext.cast_type) =
                                  "github.com/OffchainLabs/prysm/v7/"
                                  "consensus-types/primitives.ValidatorIndex" ];
}

message HistoricalBatch {
  repeated bytes block_roots = 1
      [ (ethereum.eth.ext.ssz_size) = "block_roots.size" ];
  repeated bytes state_roots = 2
      [ (ethereum.eth.ext.ssz_size) = "state_roots.size" ];
}

// The state summary object is defined for summarizing a state
// of a given slot. The summary facilitates regeneration of a
// specific state to allow easy playback using pre-saved state
// and blocks.
message StateSummary {
  // The slot of the state.
  uint64 slot = 1 [
    (ethereum.eth.ext.cast_type) =
        "github.com/OffchainLabs/prysm/v7/consensus-types/primitives.Slot"
  ];
  // The block root of the state.
  bytes root = 2;
}

message SigningData {
  // The root of the object being signed.
  bytes object_root = 1 [ (ethereum.eth.ext.ssz_size) = "32" ];
  // The domain for the particular object being signed.
  bytes domain = 2 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

message ForkData {
  // The current version of the fork.
  bytes current_version = 4 [ (ethereum.eth.ext.ssz_size) = "4" ];
  // The genesis validators root of the fork.
  bytes genesis_validators_root = 2 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

message CheckPtInfo {
  // The randao seed which the check point refers to, this will be used to
  // retrieve shuffled indices.
  bytes seed = 1;
  // The genesis root which the check point refers to. This ensures same seed
  // can't happen on different chain.
  bytes genesis_root = 2;
  // Validators that were active at that check point.
  repeated uint64 active_indices = 3;
  // Validators public keys at that check point.
  repeated bytes pub_keys = 4;
  // The fork data at that check point. This will be used to verify signatures.
  Fork fork = 5;
}

// DepositMessage serves as a subset of deposit data in order to derive the
// signing root.
message DepositMessage {
  // 48 byte BLS public key of the validator.
  bytes public_key = 1 [
    (ethereum.eth.ext.ssz_size) = "48",
    (ethereum.eth.ext.spec_name) = "pubkey"
  ];

  // A 32 byte hash of the withdrawal address public key.
  bytes withdrawal_credentials = 2 [ (ethereum.eth.ext.ssz_size) = "32" ];

  // Deposit amount in gwei.
  uint64 amount = 3;
}

// PowBlock is a definition from Bellatrix fork choice spec to represent a block
// with total difficulty in the PoW chain. Spec: class PowBlock(Container):
//    block_hash: Hash32
//    parent_hash: Hash32
//    total_difficulty: uint256
message PowBlock {
  bytes block_hash = 1 [ (ethereum.eth.ext.ssz_size) = "32" ];
  bytes parent_hash = 2 [ (ethereum.eth.ext.ssz_size) = "32" ];
  bytes total_difficulty = 3 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

// ----------------------------------------------------------------------------
// Altair
// ----------------------------------------------------------------------------

// SyncAggregatorSelectionData is used to sign over and then check whether the
// aggregator is selected within a subcommittee.
message SyncAggregatorSelectionData {
  // Slot of this signing data.
  uint64 slot = 1 [
    (ethereum.eth.ext.cast_type) =
        "github.com/OffchainLabs/prysm/v7/consensus-types/primitives.Slot"
  ];
  // Subcommittee index of this signing data.
  uint64 subcommittee_index = 2;
}

// ----------------------------------------------------------------------------
// Bellatrix
// ----------------------------------------------------------------------------


// ----------------------------------------------------------------------------
// Capella
// ----------------------------------------------------------------------------


// ----------------------------------------------------------------------------
// Deneb
// ----------------------------------------------------------------------------


// ----------------------------------------------------------------------------
// Electra
// ----------------------------------------------------------------------------


// ----------------------------------------------------------------------------
// Fulu
// ----------------------------------------------------------------------------
