// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: proto/prysm/v1alpha1/cell.proto

package eth

import (
	_ "github.com/OffchainLabs/prysm/v6/proto/eth/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CellSidecar represents a data availability cell sidecar.
type CellSidecar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction hash (can be omitted, but requires indexing transactions by their blob_versioned_hashes)
	TxHash []byte `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Cell   []byte `protobuf:"bytes,2,opt,name=cell,proto3" json:"cell,omitempty"`
	// Blob index
	BlobIndex uint32 `protobuf:"varint,3,opt,name=blob_index,json=blobIndex,proto3" json:"blob_index,omitempty"`
	// Column index
	ColumnIndex uint64 `protobuf:"varint,4,opt,name=column_index,json=columnIndex,proto3" json:"column_index,omitempty"`
	// KZG commitment
	KzgCommitment []byte `protobuf:"bytes,5,opt,name=kzg_commitment,json=kzgCommitment,proto3" json:"kzg_commitment,omitempty"`
	// KZG cell proof
	KzgCellProof  []byte `protobuf:"bytes,6,opt,name=kzg_cell_proof,json=kzgCellProof,proto3" json:"kzg_cell_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellSidecar) Reset() {
	*x = CellSidecar{}
	mi := &file_proto_prysm_v1alpha1_cell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellSidecar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellSidecar) ProtoMessage() {}

func (x *CellSidecar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prysm_v1alpha1_cell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellSidecar.ProtoReflect.Descriptor instead.
func (*CellSidecar) Descriptor() ([]byte, []int) {
	return file_proto_prysm_v1alpha1_cell_proto_rawDescGZIP(), []int{0}
}

func (x *CellSidecar) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *CellSidecar) GetCell() []byte {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *CellSidecar) GetBlobIndex() uint32 {
	if x != nil {
		return x.BlobIndex
	}
	return 0
}

func (x *CellSidecar) GetColumnIndex() uint64 {
	if x != nil {
		return x.ColumnIndex
	}
	return 0
}

func (x *CellSidecar) GetKzgCommitment() []byte {
	if x != nil {
		return x.KzgCommitment
	}
	return nil
}

func (x *CellSidecar) GetKzgCellProof() []byte {
	if x != nil {
		return x.KzgCellProof
	}
	return nil
}

var File_proto_prysm_v1alpha1_cell_proto protoreflect.FileDescriptor

const file_proto_prysm_v1alpha1_cell_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/prysm/v1alpha1/cell.proto\x12\x15ethereum.eth.v1alpha1\x1a\x1bproto/eth/ext/options.proto\"\xfa\x01\n" +
	"\vCellSidecar\x12\x1f\n" +
	"\atx_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x06txHash\x12+\n" +
	"\x04cell\x18\x02 \x01(\fB\x17\x8a\xb5\x18\x13bytes_per_cell.sizeR\x04cell\x12\x1d\n" +
	"\n" +
	"blob_index\x18\x03 \x01(\rR\tblobIndex\x12!\n" +
	"\fcolumn_index\x18\x04 \x01(\x04R\vcolumnIndex\x12-\n" +
	"\x0ekzg_commitment\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0248R\rkzgCommitment\x12,\n" +
	"\x0ekzg_cell_proof\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0248R\fkzgCellProofB\x94\x01\n" +
	"\x19org.ethereum.eth.v1alpha1B\tCellProtoP\x01Z:github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1;eth\xaa\x02\x15Ethereum.Eth.v1alpha1\xca\x02\x15Ethereum\\Eth\\v1alpha1b\x06proto3"

var (
	file_proto_prysm_v1alpha1_cell_proto_rawDescOnce sync.Once
	file_proto_prysm_v1alpha1_cell_proto_rawDescData []byte
)

func file_proto_prysm_v1alpha1_cell_proto_rawDescGZIP() []byte {
	file_proto_prysm_v1alpha1_cell_proto_rawDescOnce.Do(func() {
		file_proto_prysm_v1alpha1_cell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prysm_v1alpha1_cell_proto_rawDesc), len(file_proto_prysm_v1alpha1_cell_proto_rawDesc)))
	})
	return file_proto_prysm_v1alpha1_cell_proto_rawDescData
}

var file_proto_prysm_v1alpha1_cell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_prysm_v1alpha1_cell_proto_goTypes = []any{
	(*CellSidecar)(nil), // 0: ethereum.eth.v1alpha1.CellSidecar
}
var file_proto_prysm_v1alpha1_cell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_prysm_v1alpha1_cell_proto_init() }
func file_proto_prysm_v1alpha1_cell_proto_init() {
	if File_proto_prysm_v1alpha1_cell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prysm_v1alpha1_cell_proto_rawDesc), len(file_proto_prysm_v1alpha1_cell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_prysm_v1alpha1_cell_proto_goTypes,
		DependencyIndexes: file_proto_prysm_v1alpha1_cell_proto_depIdxs,
		MessageInfos:      file_proto_prysm_v1alpha1_cell_proto_msgTypes,
	}.Build()
	File_proto_prysm_v1alpha1_cell_proto = out.File
	file_proto_prysm_v1alpha1_cell_proto_goTypes = nil
	file_proto_prysm_v1alpha1_cell_proto_depIdxs = nil
}
