syntax = "proto3";

package ethereum.eth.v1alpha1;

import "proto/eth/ext/options.proto";

option go_package = "github.com/OffchainLabs/prysm/v7/proto/prysm/v1alpha1;eth";


// Spec:
// class AvailableAttestationData(Container):
//     slot: Slot
//     payload_present: boolean
//     beacon_block_root: Root
message AvailableAttestationData {
  uint64 slot = 1 [
    (ethereum.eth.ext.cast_type) =
        "github.com/OffchainLabs/prysm/v7/consensus-types/primitives.Slot"
  ];
  bool payload_present = 2;
  bytes beacon_block_root = 3 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

// AvailableAttestation is an aggregated available chain vote.
//
// Spec:
// class AvailableAttestation(Container):
//     aggregation_bits: Bitvector[AVAILABLE_COMMITTEE_SIZE]
//     data: AvailableAttestationData
//     signature: BLSSignature
message AvailableAttestation {
  bytes aggregation_bits = 1 [
    (ethereum.eth.ext.ssz_size) = "available_committee.size",
    (ethereum.eth.ext.cast_type) = "available_committee.type"
  ];
  AvailableAttestationData data = 2;
  bytes signature = 3 [ (ethereum.eth.ext.ssz_size) = "96" ];
}
