// Code generated by fastssz. DO NOT EDIT.
package eth

import (
	github_com_OffchainLabs_prysm_v7_consensus_types_primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the SignedExecutionProof object
func (s *SignedExecutionProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedExecutionProof object to a target array
func (s *SignedExecutionProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(108)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)
	if s.Message == nil {
		s.Message = new(ExecutionProof)
	}
	offset += s.Message.SizeSSZ()

	// Field (1) 'ValidatorIndex'
	dst = ssz.MarshalUint(dst, s.ValidatorIndex)

	// Field (2) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	dst = append(dst, s.Signature...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedExecutionProof object
func (s *SignedExecutionProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 108 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 108 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'ValidatorIndex'
	s.ValidatorIndex = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.ValidatorIndex](buf[4:12])

	// Field (2) 'Signature'
	if cap(s.Signature) == 0 {
		s.Signature = make([]byte, 0, len(buf[12:108]))
	}
	s.Signature = append(s.Signature, buf[12:108]...)

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(ExecutionProof)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedExecutionProof object
func (s *SignedExecutionProof) SizeSSZ() (size int) {
	size = 108

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(ExecutionProof)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedExecutionProof object
func (s *SignedExecutionProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedExecutionProof object with a hasher
func (s *SignedExecutionProof) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ValidatorIndex'
	ssz.PutUint(hh, s.ValidatorIndex)

	// Field (2) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	hh.PutBytes(s.Signature)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionProof object
func (e *ExecutionProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionProof object to a target array
func (e *ExecutionProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(37)

	// Offset (0) 'ProofData'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.ProofData)

	// Field (1) 'ProofType'
	if size := len(e.ProofType); size != 1 {
		err = ssz.ErrBytesLengthFn("--.ProofType", size, 1)
		return
	}
	dst = append(dst, e.ProofType...)

	// Field (2) 'PublicInput'
	if e.PublicInput == nil {
		e.PublicInput = new(PublicInput)
	}
	if dst, err = e.PublicInput.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (0) 'ProofData'
	if size := len(e.ProofData); size > 409600 {
		err = ssz.ErrBytesLengthFn("--.ProofData", size, 409600)
		return
	}
	dst = append(dst, e.ProofData...)

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionProof object
func (e *ExecutionProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 37 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'ProofData'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 37 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'ProofType'
	if cap(e.ProofType) == 0 {
		e.ProofType = make([]byte, 0, len(buf[4:5]))
	}
	e.ProofType = append(e.ProofType, buf[4:5]...)

	// Field (2) 'PublicInput'
	if e.PublicInput == nil {
		e.PublicInput = new(PublicInput)
	}
	if err = e.PublicInput.UnmarshalSSZ(buf[5:37]); err != nil {
		return err
	}

	// Field (0) 'ProofData'
	{
		buf = tail[o0:]
		if len(buf) > 409600 {
			return ssz.ErrBytesLength
		}
		if cap(e.ProofData) == 0 {
			e.ProofData = make([]byte, 0, len(buf))
		}
		e.ProofData = append(e.ProofData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionProof object
func (e *ExecutionProof) SizeSSZ() (size int) {
	size = 37

	// Field (0) 'ProofData'
	size += len(e.ProofData)

	return
}

// HashTreeRoot ssz hashes the ExecutionProof object
func (e *ExecutionProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionProof object with a hasher
func (e *ExecutionProof) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ProofData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(e.ProofData))
		if byteLen > 409600 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(e.ProofData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (409600+31)/32)
	}

	// Field (1) 'ProofType'
	if size := len(e.ProofType); size != 1 {
		err = ssz.ErrBytesLengthFn("--.ProofType", size, 1)
		return
	}
	hh.PutBytes(e.ProofType)

	// Field (2) 'PublicInput'
	if err = e.PublicInput.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the PublicInput object
func (p *PublicInput) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the PublicInput object to a target array
func (p *PublicInput) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'NewPayloadRequestRoot'
	if size := len(p.NewPayloadRequestRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.NewPayloadRequestRoot", size, 32)
		return
	}
	dst = append(dst, p.NewPayloadRequestRoot...)

	return
}

// UnmarshalSSZ ssz unmarshals the PublicInput object
func (p *PublicInput) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 32 {
		return ssz.ErrSize
	}

	// Field (0) 'NewPayloadRequestRoot'
	if cap(p.NewPayloadRequestRoot) == 0 {
		p.NewPayloadRequestRoot = make([]byte, 0, len(buf[0:32]))
	}
	p.NewPayloadRequestRoot = append(p.NewPayloadRequestRoot, buf[0:32]...)

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the PublicInput object
func (p *PublicInput) SizeSSZ() (size int) {
	size = 32
	return
}

// HashTreeRoot ssz hashes the PublicInput object
func (p *PublicInput) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the PublicInput object with a hasher
func (p *PublicInput) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'NewPayloadRequestRoot'
	if size := len(p.NewPayloadRequestRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.NewPayloadRequestRoot", size, 32)
		return
	}
	hh.PutBytes(p.NewPayloadRequestRoot)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ProofByRootIdentifier object
func (p *ProofByRootIdentifier) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the ProofByRootIdentifier object to a target array
func (p *ProofByRootIdentifier) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(36)

	// Field (0) 'BlockRoot'
	if size := len(p.BlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockRoot", size, 32)
		return
	}
	dst = append(dst, p.BlockRoot...)

	// Offset (1) 'ProofTypes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.ProofTypes)

	// Field (1) 'ProofTypes'
	if size := len(p.ProofTypes); size > 4 {
		err = ssz.ErrBytesLengthFn("--.ProofTypes", size, 4)
		return
	}
	dst = append(dst, p.ProofTypes...)

	return
}

// UnmarshalSSZ ssz unmarshals the ProofByRootIdentifier object
func (p *ProofByRootIdentifier) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 36 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'BlockRoot'
	if cap(p.BlockRoot) == 0 {
		p.BlockRoot = make([]byte, 0, len(buf[0:32]))
	}
	p.BlockRoot = append(p.BlockRoot, buf[0:32]...)

	// Offset (1) 'ProofTypes'
	if o1 = ssz.ReadOffset(buf[32:36]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 36 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'ProofTypes'
	{
		buf = tail[o1:]
		if len(buf) > 4 {
			return ssz.ErrBytesLength
		}
		if cap(p.ProofTypes) == 0 {
			p.ProofTypes = make([]byte, 0, len(buf))
		}
		p.ProofTypes = append(p.ProofTypes, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ProofByRootIdentifier object
func (p *ProofByRootIdentifier) SizeSSZ() (size int) {
	size = 36

	// Field (1) 'ProofTypes'
	size += len(p.ProofTypes)

	return
}

// HashTreeRoot ssz hashes the ProofByRootIdentifier object
func (p *ProofByRootIdentifier) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the ProofByRootIdentifier object with a hasher
func (p *ProofByRootIdentifier) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'BlockRoot'
	if size := len(p.BlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockRoot", size, 32)
		return
	}
	hh.PutBytes(p.BlockRoot)

	// Field (1) 'ProofTypes'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(p.ProofTypes))
		if byteLen > 4 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(p.ProofTypes)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (4+31)/32)
	}

	hh.Merkleize(indx)
	return
}
