// NOTE: This file is auto-generated by sszgen, but modified manually
// to handle the alias type ExecutionProofId which is based on uint8.
package eth

import (
	github_com_OffchainLabs_prysm_v7_consensus_types_primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the ExecutionProof object
func (e *ExecutionProof) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionProof object to a target array
func (e *ExecutionProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(77)

	// Field (0) 'ProofId'
	dst = ssz.MarshalUint8(dst, uint8(e.ProofId))

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(e.Slot))

	// Field (2) 'BlockHash'
	if size := len(e.BlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockHash", size, 32)
		return
	}
	dst = append(dst, e.BlockHash...)

	// Field (3) 'BlockRoot'
	if size := len(e.BlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockRoot", size, 32)
		return
	}
	dst = append(dst, e.BlockRoot...)

	// Offset (4) 'ProofData'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.ProofData)

	// Field (4) 'ProofData'
	if size := len(e.ProofData); size > 1048576 {
		err = ssz.ErrBytesLengthFn("--.ProofData", size, 1048576)
		return
	}
	dst = append(dst, e.ProofData...)

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionProof object
func (e *ExecutionProof) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 77 {
		return ssz.ErrSize
	}

	tail := buf
	var o4 uint64

	// Field (0) 'ProofId'
	e.ProofId = github_com_OffchainLabs_prysm_v7_consensus_types_primitives.ExecutionProofId(ssz.UnmarshallUint8(buf[0:1]))

	// Field (1) 'Slot'
	e.Slot = github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Slot(ssz.UnmarshallUint64(buf[1:9]))

	// Field (2) 'BlockHash'
	if cap(e.BlockHash) == 0 {
		e.BlockHash = make([]byte, 0, len(buf[9:41]))
	}
	e.BlockHash = append(e.BlockHash, buf[9:41]...)

	// Field (3) 'BlockRoot'
	if cap(e.BlockRoot) == 0 {
		e.BlockRoot = make([]byte, 0, len(buf[41:73]))
	}
	e.BlockRoot = append(e.BlockRoot, buf[41:73]...)

	// Offset (4) 'ProofData'
	if o4 = ssz.ReadOffset(buf[73:77]); o4 > size {
		return ssz.ErrOffset
	}

	if o4 != 77 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (4) 'ProofData'
	{
		buf = tail[o4:]
		if len(buf) > 1048576 {
			return ssz.ErrBytesLength
		}
		if cap(e.ProofData) == 0 {
			e.ProofData = make([]byte, 0, len(buf))
		}
		e.ProofData = append(e.ProofData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionProof object
func (e *ExecutionProof) SizeSSZ() (size int) {
	size = 77

	// Field (4) 'ProofData'
	size += len(e.ProofData)

	return
}

// HashTreeRoot ssz hashes the ExecutionProof object
func (e *ExecutionProof) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionProof object with a hasher
func (e *ExecutionProof) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ProofId'
	hh.PutUint8(uint8(e.ProofId))

	// Field (1) 'Slot'
	hh.PutUint64(uint64(e.Slot))

	// Field (2) 'BlockHash'
	if size := len(e.BlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockHash", size, 32)
		return
	}
	hh.PutBytes(e.BlockHash)

	// Field (3) 'BlockRoot'
	if size := len(e.BlockRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockRoot", size, 32)
		return
	}
	hh.PutBytes(e.BlockRoot)

	// Field (4) 'ProofData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(e.ProofData))
		if byteLen > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(e.ProofData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1048576+31)/32)
	}

	hh.Merkleize(indx)
	return
}
