//go:build minimal

// Code generated by fastssz. DO NOT EDIT.
package eth

import (
	github_com_OffchainLabs_prysm_v7_consensus_types_primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the RequestAuthV1 object
func (r *RequestAuthV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(r)
}

// MarshalSSZTo ssz marshals the RequestAuthV1 object to a target array
func (r *RequestAuthV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Offset (0) 'Data'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(r.Data)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint(dst, r.Slot)

	// Field (0) 'Data'
	if size := len(r.Data); size > 4096 {
		err = ssz.ErrBytesLengthFn("--.Data", size, 4096)
		return
	}
	dst = append(dst, r.Data...)

	return
}

// UnmarshalSSZ ssz unmarshals the RequestAuthV1 object
func (r *RequestAuthV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Data'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Slot'
	r.Slot = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Slot](buf[4:12])

	// Field (0) 'Data'
	{
		buf = tail[o0:]
		if len(buf) > 4096 {
			return ssz.ErrBytesLength
		}
		if cap(r.Data) == 0 {
			r.Data = make([]byte, 0, len(buf))
		}
		r.Data = append(r.Data, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the RequestAuthV1 object
func (r *RequestAuthV1) SizeSSZ() (size int) {
	size = 12

	// Field (0) 'Data'
	size += len(r.Data)

	return
}

// HashTreeRoot ssz hashes the RequestAuthV1 object
func (r *RequestAuthV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(r)
}

// HashTreeRootWith ssz hashes the RequestAuthV1 object with a hasher
func (r *RequestAuthV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(r.Data))
		if byteLen > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(r.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (4096+31)/32)
	}

	// Field (1) 'Slot'
	ssz.PutUint(hh, r.Slot)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the SignedRequestAuthV1 object
func (s *SignedRequestAuthV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedRequestAuthV1 object to a target array
func (s *SignedRequestAuthV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Offset (0) 'Message'
	dst = ssz.WriteOffset(dst, offset)
	if s.Message == nil {
		s.Message = new(RequestAuthV1)
	}
	offset += s.Message.SizeSSZ()

	// Field (1) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	dst = append(dst, s.Signature...)

	// Field (0) 'Message'
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedRequestAuthV1 object
func (s *SignedRequestAuthV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Message'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Signature'
	if cap(s.Signature) == 0 {
		s.Signature = make([]byte, 0, len(buf[4:100]))
	}
	s.Signature = append(s.Signature, buf[4:100]...)

	// Field (0) 'Message'
	{
		buf = tail[o0:]
		if s.Message == nil {
			s.Message = new(RequestAuthV1)
		}
		if err = s.Message.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedRequestAuthV1 object
func (s *SignedRequestAuthV1) SizeSSZ() (size int) {
	size = 100

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(RequestAuthV1)
	}
	size += s.Message.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SignedRequestAuthV1 object
func (s *SignedRequestAuthV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedRequestAuthV1 object with a hasher
func (s *SignedRequestAuthV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	if size := len(s.Signature); size != 96 {
		err = ssz.ErrBytesLengthFn("--.Signature", size, 96)
		return
	}
	hh.PutBytes(s.Signature)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferencesV1 object to a target array
func (b *BuilderPreferencesV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'MaxExecutionPayment'
	dst = ssz.MarshalUint(dst, b.MaxExecutionPayment)

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return ssz.ErrSize
	}

	// Field (0) 'MaxExecutionPayment'
	b.MaxExecutionPayment = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Gwei](buf[0:8])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) SizeSSZ() (size int) {
	size = 8
	return
}

// HashTreeRoot ssz hashes the BuilderPreferencesV1 object
func (b *BuilderPreferencesV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferencesV1 object with a hasher
func (b *BuilderPreferencesV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'MaxExecutionPayment'
	ssz.PutUint(hh, b.MaxExecutionPayment)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPreferencesRequestV1 object to a target array
func (b *BuilderPreferencesRequestV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(12)

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferencesV1)
	}
	if dst, err = b.Preferences.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'Auth'
	dst = ssz.WriteOffset(dst, offset)
	if b.Auth == nil {
		b.Auth = new(SignedRequestAuthV1)
	}
	offset += b.Auth.SizeSSZ()

	// Field (1) 'Auth'
	if dst, err = b.Auth.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 12 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Preferences'
	if b.Preferences == nil {
		b.Preferences = new(BuilderPreferencesV1)
	}
	if err = b.Preferences.UnmarshalSSZ(buf[0:8]); err != nil {
		return err
	}

	// Offset (1) 'Auth'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 12 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Auth'
	{
		buf = tail[o1:]
		if b.Auth == nil {
			b.Auth = new(SignedRequestAuthV1)
		}
		if err = b.Auth.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) SizeSSZ() (size int) {
	size = 12

	// Field (1) 'Auth'
	if b.Auth == nil {
		b.Auth = new(SignedRequestAuthV1)
	}
	size += b.Auth.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BuilderPreferencesRequestV1 object
func (b *BuilderPreferencesRequestV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPreferencesRequestV1 object with a hasher
func (b *BuilderPreferencesRequestV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Preferences'
	if err = b.Preferences.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Auth'
	if err = b.Auth.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ProduceBuilderEntryV1 object
func (p *ProduceBuilderEntryV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the ProduceBuilderEntryV1 object to a target array
func (p *ProduceBuilderEntryV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(72)

	// Offset (0) 'Url'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.Url)

	// Offset (1) 'Request'
	dst = ssz.WriteOffset(dst, offset)
	if p.Request == nil {
		p.Request = new(BuilderPreferencesRequestV1)
	}
	offset += p.Request.SizeSSZ()

	// Field (2) 'MinBid'
	dst = ssz.MarshalUint(dst, p.MinBid)

	// Field (3) 'BuilderBoostFactor'
	dst = ssz.MarshalUint(dst, p.BuilderBoostFactor)

	// Field (4) 'Pubkey'
	if size := len(p.Pubkey); size != 48 {
		err = ssz.ErrBytesLengthFn("--.Pubkey", size, 48)
		return
	}
	dst = append(dst, p.Pubkey...)

	// Field (0) 'Url'
	if size := len(p.Url); size > 2048 {
		err = ssz.ErrBytesLengthFn("--.Url", size, 2048)
		return
	}
	dst = append(dst, p.Url...)

	// Field (1) 'Request'
	if dst, err = p.Request.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ProduceBuilderEntryV1 object
func (p *ProduceBuilderEntryV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 72 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Url'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 72 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Request'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (2) 'MinBid'
	p.MinBid = ssz.UnmarshallUint[github_com_OffchainLabs_prysm_v7_consensus_types_primitives.Gwei](buf[8:16])

	// Field (3) 'BuilderBoostFactor'
	p.BuilderBoostFactor = ssz.UnmarshallUint[uint64](buf[16:24])

	// Field (4) 'Pubkey'
	if cap(p.Pubkey) == 0 {
		p.Pubkey = make([]byte, 0, len(buf[24:72]))
	}
	p.Pubkey = append(p.Pubkey, buf[24:72]...)

	// Field (0) 'Url'
	{
		buf = tail[o0:o1]
		if len(buf) > 2048 {
			return ssz.ErrBytesLength
		}
		if cap(p.Url) == 0 {
			p.Url = make([]byte, 0, len(buf))
		}
		p.Url = append(p.Url, buf...)
	}

	// Field (1) 'Request'
	{
		buf = tail[o1:]
		if p.Request == nil {
			p.Request = new(BuilderPreferencesRequestV1)
		}
		if err = p.Request.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ProduceBuilderEntryV1 object
func (p *ProduceBuilderEntryV1) SizeSSZ() (size int) {
	size = 72

	// Field (0) 'Url'
	size += len(p.Url)

	// Field (1) 'Request'
	if p.Request == nil {
		p.Request = new(BuilderPreferencesRequestV1)
	}
	size += p.Request.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the ProduceBuilderEntryV1 object
func (p *ProduceBuilderEntryV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the ProduceBuilderEntryV1 object with a hasher
func (p *ProduceBuilderEntryV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Url'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(p.Url))
		if byteLen > 2048 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.AppendBytes32(p.Url)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (2048+31)/32)
	}

	// Field (1) 'Request'
	if err = p.Request.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'MinBid'
	ssz.PutUint(hh, p.MinBid)

	// Field (3) 'BuilderBoostFactor'
	ssz.PutUint(hh, p.BuilderBoostFactor)

	// Field (4) 'Pubkey'
	if size := len(p.Pubkey); size != 48 {
		err = ssz.ErrBytesLengthFn("--.Pubkey", size, 48)
		return
	}
	hh.PutBytes(p.Pubkey)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ProduceBuilderEntryListV1 object
func (p *ProduceBuilderEntryListV1) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the ProduceBuilderEntryListV1 object to a target array
func (p *ProduceBuilderEntryListV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Entries'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(p.Entries); ii++ {
		offset += 4
		offset += p.Entries[ii].SizeSSZ()
	}

	// Field (0) 'Entries'
	if size := len(p.Entries); size > 64 {
		err = ssz.ErrListTooBigFn("--.Entries", size, 64)
		return
	}
	{
		offset = 4 * len(p.Entries)
		for ii := 0; ii < len(p.Entries); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += p.Entries[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(p.Entries); ii++ {
		if dst, err = p.Entries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ProduceBuilderEntryListV1 object
func (p *ProduceBuilderEntryListV1) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Entries'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Entries'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		p.Entries = make([]*ProduceBuilderEntryV1, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if p.Entries[indx] == nil {
				p.Entries[indx] = new(ProduceBuilderEntryV1)
			}
			if err = p.Entries[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ProduceBuilderEntryListV1 object
func (p *ProduceBuilderEntryListV1) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Entries'
	for ii := 0; ii < len(p.Entries); ii++ {
		size += 4
		size += p.Entries[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ProduceBuilderEntryListV1 object
func (p *ProduceBuilderEntryListV1) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the ProduceBuilderEntryListV1 object with a hasher
func (p *ProduceBuilderEntryListV1) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Entries'
	{
		subIndx := hh.Index()
		num := uint64(len(p.Entries))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range p.Entries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	hh.Merkleize(indx)
	return
}
