load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["handler.go"],
    embedsrcs = [
        "static/app.css",
        "static/app.js",
        "static/fonts-license.txt",
        "static/index.html",
        "static/plexmono-400.woff2",
        "static/plexmono-500.woff2",
        "static/plexsans.woff2",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/beacon-chain/rpc/doctorpeer",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["handler_test.go"],
    embed = [":go_default_library"],
    deps = [
        "//testing/assert:go_default_library",
        "//testing/require:go_default_library",
    ],
)
