// Code generated by fastssz. DO NOT EDIT.
package enginev1

import (
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the GetPayloadV2ResponseSSZ object
func (g *GetPayloadV2ResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV2ResponseSSZ object to a target array
func (g *GetPayloadV2ResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(36)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadCapella)
	}
	offset += g.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, g.BlockValue...)

	// Field (0) 'Payload'
	if dst, err = g.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV2ResponseSSZ object
func (g *GetPayloadV2ResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 36 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 36 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(g.BlockValue) == 0 {
		g.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	g.BlockValue = append(g.BlockValue, buf[4:36]...)

	// Field (0) 'Payload'
	{
		buf = tail[o0:]
		if g.Payload == nil {
			g.Payload = new(ExecutionPayloadCapella)
		}
		if err = g.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV2ResponseSSZ object
func (g *GetPayloadV2ResponseSSZ) SizeSSZ() (size int) {
	size = 36

	// Field (0) 'Payload'
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadCapella)
	}
	size += g.Payload.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GetPayloadV2ResponseSSZ object
func (g *GetPayloadV2ResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV2ResponseSSZ object with a hasher
func (g *GetPayloadV2ResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = g.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(g.BlockValue)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the GetPayloadV3ResponseSSZ object
func (g *GetPayloadV3ResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV3ResponseSSZ object to a target array
func (g *GetPayloadV3ResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(41)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	offset += g.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, g.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundle)
	}
	offset += g.BlobsBundle.SizeSSZ()

	// Field (3) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, g.ShouldOverrideBuilder)

	// Field (0) 'Payload'
	if dst, err = g.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = g.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV3ResponseSSZ object
func (g *GetPayloadV3ResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 41 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 41 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(g.BlockValue) == 0 {
		g.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	g.BlockValue = append(g.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (3) 'ShouldOverrideBuilder'
	g.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[40:41])
	if err != nil {
		return err
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if g.Payload == nil {
			g.Payload = new(ExecutionPayloadDeneb)
		}
		if err = g.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:]
		if g.BlobsBundle == nil {
			g.BlobsBundle = new(BlobsBundle)
		}
		if err = g.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV3ResponseSSZ object
func (g *GetPayloadV3ResponseSSZ) SizeSSZ() (size int) {
	size = 41

	// Field (0) 'Payload'
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	size += g.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundle)
	}
	size += g.BlobsBundle.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GetPayloadV3ResponseSSZ object
func (g *GetPayloadV3ResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV3ResponseSSZ object with a hasher
func (g *GetPayloadV3ResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = g.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(g.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = g.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ShouldOverrideBuilder'
	hh.PutBool(g.ShouldOverrideBuilder)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the GetPayloadV4ResponseSSZ object
func (g *GetPayloadV4ResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV4ResponseSSZ object to a target array
func (g *GetPayloadV4ResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(45)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	offset += g.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, g.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundle)
	}
	offset += g.BlobsBundle.SizeSSZ()

	// Field (3) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, g.ShouldOverrideBuilder)

	// Offset (4) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	offset += g.ExecutionRequests.SizeSSZ()

	// Field (0) 'Payload'
	if dst, err = g.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = g.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'ExecutionRequests'
	if dst, err = g.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV4ResponseSSZ object
func (g *GetPayloadV4ResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 45 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2, o4 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 45 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(g.BlockValue) == 0 {
		g.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	g.BlockValue = append(g.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (3) 'ShouldOverrideBuilder'
	g.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[40:41])
	if err != nil {
		return err
	}

	// Offset (4) 'ExecutionRequests'
	if o4 = ssz.ReadOffset(buf[41:45]); o4 > size || o2 > o4 {
		return ssz.ErrOffset
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if g.Payload == nil {
			g.Payload = new(ExecutionPayloadDeneb)
		}
		if err = g.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o4]
		if g.BlobsBundle == nil {
			g.BlobsBundle = new(BlobsBundle)
		}
		if err = g.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (4) 'ExecutionRequests'
	{
		buf = tail[o4:]
		if g.ExecutionRequests == nil {
			g.ExecutionRequests = new(ExecutionRequests)
		}
		if err = g.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV4ResponseSSZ object
func (g *GetPayloadV4ResponseSSZ) SizeSSZ() (size int) {
	size = 45

	// Field (0) 'Payload'
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	size += g.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundle)
	}
	size += g.BlobsBundle.SizeSSZ()

	// Field (4) 'ExecutionRequests'
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	size += g.ExecutionRequests.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GetPayloadV4ResponseSSZ object
func (g *GetPayloadV4ResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV4ResponseSSZ object with a hasher
func (g *GetPayloadV4ResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = g.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(g.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = g.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ShouldOverrideBuilder'
	hh.PutBool(g.ShouldOverrideBuilder)

	// Field (4) 'ExecutionRequests'
	if err = g.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the GetPayloadV5ResponseSSZ object
func (g *GetPayloadV5ResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV5ResponseSSZ object to a target array
func (g *GetPayloadV5ResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(45)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	offset += g.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, g.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundleV2)
	}
	offset += g.BlobsBundle.SizeSSZ()

	// Field (3) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, g.ShouldOverrideBuilder)

	// Offset (4) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	offset += g.ExecutionRequests.SizeSSZ()

	// Field (0) 'Payload'
	if dst, err = g.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = g.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'ExecutionRequests'
	if dst, err = g.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV5ResponseSSZ object
func (g *GetPayloadV5ResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 45 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2, o4 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 45 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(g.BlockValue) == 0 {
		g.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	g.BlockValue = append(g.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (3) 'ShouldOverrideBuilder'
	g.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[40:41])
	if err != nil {
		return err
	}

	// Offset (4) 'ExecutionRequests'
	if o4 = ssz.ReadOffset(buf[41:45]); o4 > size || o2 > o4 {
		return ssz.ErrOffset
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if g.Payload == nil {
			g.Payload = new(ExecutionPayloadDeneb)
		}
		if err = g.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o4]
		if g.BlobsBundle == nil {
			g.BlobsBundle = new(BlobsBundleV2)
		}
		if err = g.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (4) 'ExecutionRequests'
	{
		buf = tail[o4:]
		if g.ExecutionRequests == nil {
			g.ExecutionRequests = new(ExecutionRequests)
		}
		if err = g.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV5ResponseSSZ object
func (g *GetPayloadV5ResponseSSZ) SizeSSZ() (size int) {
	size = 45

	// Field (0) 'Payload'
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadDeneb)
	}
	size += g.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundleV2)
	}
	size += g.BlobsBundle.SizeSSZ()

	// Field (4) 'ExecutionRequests'
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	size += g.ExecutionRequests.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GetPayloadV5ResponseSSZ object
func (g *GetPayloadV5ResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV5ResponseSSZ object with a hasher
func (g *GetPayloadV5ResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = g.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(g.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = g.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ShouldOverrideBuilder'
	hh.PutBool(g.ShouldOverrideBuilder)

	// Field (4) 'ExecutionRequests'
	if err = g.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the GetPayloadV6ResponseSSZ object
func (g *GetPayloadV6ResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetPayloadV6ResponseSSZ object to a target array
func (g *GetPayloadV6ResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(45)

	// Offset (0) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadGloas)
	}
	offset += g.Payload.SizeSSZ()

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	dst = append(dst, g.BlockValue...)

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundleV2)
	}
	offset += g.BlobsBundle.SizeSSZ()

	// Field (3) 'ShouldOverrideBuilder'
	dst = ssz.MarshalBool(dst, g.ShouldOverrideBuilder)

	// Offset (4) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	offset += g.ExecutionRequests.SizeSSZ()

	// Field (0) 'Payload'
	if dst, err = g.Payload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = g.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'ExecutionRequests'
	if dst, err = g.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetPayloadV6ResponseSSZ object
func (g *GetPayloadV6ResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 45 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o2, o4 uint64

	// Offset (0) 'Payload'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 45 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'BlockValue'
	if cap(g.BlockValue) == 0 {
		g.BlockValue = make([]byte, 0, len(buf[4:36]))
	}
	g.BlockValue = append(g.BlockValue, buf[4:36]...)

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[36:40]); o2 > size || o0 > o2 {
		return ssz.ErrOffset
	}

	// Field (3) 'ShouldOverrideBuilder'
	g.ShouldOverrideBuilder, err = ssz.DecodeBool(buf[40:41])
	if err != nil {
		return err
	}

	// Offset (4) 'ExecutionRequests'
	if o4 = ssz.ReadOffset(buf[41:45]); o4 > size || o2 > o4 {
		return ssz.ErrOffset
	}

	// Field (0) 'Payload'
	{
		buf = tail[o0:o2]
		if g.Payload == nil {
			g.Payload = new(ExecutionPayloadGloas)
		}
		if err = g.Payload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o4]
		if g.BlobsBundle == nil {
			g.BlobsBundle = new(BlobsBundleV2)
		}
		if err = g.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (4) 'ExecutionRequests'
	{
		buf = tail[o4:]
		if g.ExecutionRequests == nil {
			g.ExecutionRequests = new(ExecutionRequests)
		}
		if err = g.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetPayloadV6ResponseSSZ object
func (g *GetPayloadV6ResponseSSZ) SizeSSZ() (size int) {
	size = 45

	// Field (0) 'Payload'
	if g.Payload == nil {
		g.Payload = new(ExecutionPayloadGloas)
	}
	size += g.Payload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if g.BlobsBundle == nil {
		g.BlobsBundle = new(BlobsBundleV2)
	}
	size += g.BlobsBundle.SizeSSZ()

	// Field (4) 'ExecutionRequests'
	if g.ExecutionRequests == nil {
		g.ExecutionRequests = new(ExecutionRequests)
	}
	size += g.ExecutionRequests.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the GetPayloadV6ResponseSSZ object
func (g *GetPayloadV6ResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetPayloadV6ResponseSSZ object with a hasher
func (g *GetPayloadV6ResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Payload'
	if err = g.Payload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'BlockValue'
	if size := len(g.BlockValue); size != 32 {
		err = ssz.ErrBytesLengthFn("--.BlockValue", size, 32)
		return
	}
	hh.PutBytes(g.BlockValue)

	// Field (2) 'BlobsBundle'
	if err = g.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ShouldOverrideBuilder'
	hh.PutBool(g.ShouldOverrideBuilder)

	// Field (4) 'ExecutionRequests'
	if err = g.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}
