// Code generated by fastssz. DO NOT EDIT.
// Hash: 4d531eea8b79f46290f6865e4fea1a9309cfd4cf9e440bd688c78a6f854845b8
package enginev1

import (
	ssz "github.com/prysmaticlabs/fastssz"
)

// MarshalSSZ ssz marshals the ForkchoiceState object
func (f *ForkchoiceState) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceState object to a target array
func (f *ForkchoiceState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'HeadBlockHash'
	if size := len(f.HeadBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.HeadBlockHash", size, 32)
		return
	}
	dst = append(dst, f.HeadBlockHash...)

	// Field (1) 'SafeBlockHash'
	if size := len(f.SafeBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.SafeBlockHash", size, 32)
		return
	}
	dst = append(dst, f.SafeBlockHash...)

	// Field (2) 'FinalizedBlockHash'
	if size := len(f.FinalizedBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.FinalizedBlockHash", size, 32)
		return
	}
	dst = append(dst, f.FinalizedBlockHash...)

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceState object
func (f *ForkchoiceState) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 96 {
		return ssz.ErrSize
	}

	// Field (0) 'HeadBlockHash'
	if cap(f.HeadBlockHash) == 0 {
		f.HeadBlockHash = make([]byte, 0, len(buf[0:32]))
	}
	f.HeadBlockHash = append(f.HeadBlockHash, buf[0:32]...)

	// Field (1) 'SafeBlockHash'
	if cap(f.SafeBlockHash) == 0 {
		f.SafeBlockHash = make([]byte, 0, len(buf[32:64]))
	}
	f.SafeBlockHash = append(f.SafeBlockHash, buf[32:64]...)

	// Field (2) 'FinalizedBlockHash'
	if cap(f.FinalizedBlockHash) == 0 {
		f.FinalizedBlockHash = make([]byte, 0, len(buf[64:96]))
	}
	f.FinalizedBlockHash = append(f.FinalizedBlockHash, buf[64:96]...)

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceState object
func (f *ForkchoiceState) SizeSSZ() (size int) {
	size = 96
	return
}

// HashTreeRoot ssz hashes the ForkchoiceState object
func (f *ForkchoiceState) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceState object with a hasher
func (f *ForkchoiceState) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'HeadBlockHash'
	if size := len(f.HeadBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.HeadBlockHash", size, 32)
		return
	}
	hh.PutBytes(f.HeadBlockHash)

	// Field (1) 'SafeBlockHash'
	if size := len(f.SafeBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.SafeBlockHash", size, 32)
		return
	}
	hh.PutBytes(f.SafeBlockHash)

	// Field (2) 'FinalizedBlockHash'
	if size := len(f.FinalizedBlockHash); size != 32 {
		err = ssz.ErrBytesLengthFn("--.FinalizedBlockHash", size, 32)
		return
	}
	hh.PutBytes(f.FinalizedBlockHash)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the PayloadStatusV1SSZ object
func (p *PayloadStatusV1SSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the PayloadStatusV1SSZ object to a target array
func (p *PayloadStatusV1SSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(9)

	// Field (0) 'Status'
	dst = ssz.MarshalUint8(dst, p.Status)

	// Offset (1) 'LatestValidHash'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.LatestValidHash) * 32

	// Offset (2) 'ValidationError'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.ValidationError)

	// Field (1) 'LatestValidHash'
	if size := len(p.LatestValidHash); size > 1 {
		err = ssz.ErrListTooBigFn("--.LatestValidHash", size, 1)
		return
	}
	for ii := 0; ii < len(p.LatestValidHash); ii++ {
		if size := len(p.LatestValidHash[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("--.LatestValidHash[ii]", size, 32)
			return
		}
		dst = append(dst, p.LatestValidHash[ii]...)
	}

	// Field (2) 'ValidationError'
	if size := len(p.ValidationError); size > 1024 {
		err = ssz.ErrBytesLengthFn("--.ValidationError", size, 1024)
		return
	}
	dst = append(dst, p.ValidationError...)

	return
}

// UnmarshalSSZ ssz unmarshals the PayloadStatusV1SSZ object
func (p *PayloadStatusV1SSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 9 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2 uint64

	// Field (0) 'Status'
	p.Status = ssz.UnmarshallUint8(buf[0:1])

	// Offset (1) 'LatestValidHash'
	if o1 = ssz.ReadOffset(buf[1:5]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 9 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'ValidationError'
	if o2 = ssz.ReadOffset(buf[5:9]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (1) 'LatestValidHash'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 32, 1)
		if err != nil {
			return err
		}
		p.LatestValidHash = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(p.LatestValidHash[ii]) == 0 {
				p.LatestValidHash[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			p.LatestValidHash[ii] = append(p.LatestValidHash[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (2) 'ValidationError'
	{
		buf = tail[o2:]
		if len(buf) > 1024 {
			return ssz.ErrBytesLength
		}
		if cap(p.ValidationError) == 0 {
			p.ValidationError = make([]byte, 0, len(buf))
		}
		p.ValidationError = append(p.ValidationError, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the PayloadStatusV1SSZ object
func (p *PayloadStatusV1SSZ) SizeSSZ() (size int) {
	size = 9

	// Field (1) 'LatestValidHash'
	size += len(p.LatestValidHash) * 32

	// Field (2) 'ValidationError'
	size += len(p.ValidationError)

	return
}

// HashTreeRoot ssz hashes the PayloadStatusV1SSZ object
func (p *PayloadStatusV1SSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the PayloadStatusV1SSZ object with a hasher
func (p *PayloadStatusV1SSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Status'
	hh.PutUint8(p.Status)

	// Field (1) 'LatestValidHash'
	{
		if size := len(p.LatestValidHash); size > 1 {
			err = ssz.ErrListTooBigFn("--.LatestValidHash", size, 1)
			return
		}
		subIndx := hh.Index()
		for _, i := range p.LatestValidHash {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}

		numItems := uint64(len(p.LatestValidHash))
		hh.MerkleizeWithMixin(subIndx, numItems, 1)
	}

	// Field (2) 'ValidationError'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(p.ValidationError))
		if byteLen > 1024 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(p.ValidationError)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1024+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ForkchoiceUpdatedResponseSSZ object
func (f *ForkchoiceUpdatedResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceUpdatedResponseSSZ object to a target array
func (f *ForkchoiceUpdatedResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'PayloadStatus'
	dst = ssz.WriteOffset(dst, offset)
	if f.PayloadStatus == nil {
		f.PayloadStatus = new(PayloadStatusV1SSZ)
	}
	offset += f.PayloadStatus.SizeSSZ()

	// Offset (1) 'PayloadId'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(f.PayloadId) * 8

	// Field (0) 'PayloadStatus'
	if dst, err = f.PayloadStatus.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'PayloadId'
	if size := len(f.PayloadId); size > 1 {
		err = ssz.ErrListTooBigFn("--.PayloadId", size, 1)
		return
	}
	for ii := 0; ii < len(f.PayloadId); ii++ {
		if size := len(f.PayloadId[ii]); size != 8 {
			err = ssz.ErrBytesLengthFn("--.PayloadId[ii]", size, 8)
			return
		}
		dst = append(dst, f.PayloadId[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceUpdatedResponseSSZ object
func (f *ForkchoiceUpdatedResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'PayloadStatus'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'PayloadId'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'PayloadStatus'
	{
		buf = tail[o0:o1]
		if f.PayloadStatus == nil {
			f.PayloadStatus = new(PayloadStatusV1SSZ)
		}
		if err = f.PayloadStatus.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (1) 'PayloadId'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 8, 1)
		if err != nil {
			return err
		}
		f.PayloadId = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(f.PayloadId[ii]) == 0 {
				f.PayloadId[ii] = make([]byte, 0, len(buf[ii*8:(ii+1)*8]))
			}
			f.PayloadId[ii] = append(f.PayloadId[ii], buf[ii*8:(ii+1)*8]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceUpdatedResponseSSZ object
func (f *ForkchoiceUpdatedResponseSSZ) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'PayloadStatus'
	if f.PayloadStatus == nil {
		f.PayloadStatus = new(PayloadStatusV1SSZ)
	}
	size += f.PayloadStatus.SizeSSZ()

	// Field (1) 'PayloadId'
	size += len(f.PayloadId) * 8

	return
}

// HashTreeRoot ssz hashes the ForkchoiceUpdatedResponseSSZ object
func (f *ForkchoiceUpdatedResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceUpdatedResponseSSZ object with a hasher
func (f *ForkchoiceUpdatedResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'PayloadStatus'
	if err = f.PayloadStatus.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadId'
	{
		if size := len(f.PayloadId); size > 1 {
			err = ssz.ErrListTooBigFn("--.PayloadId", size, 1)
			return
		}
		subIndx := hh.Index()
		for _, i := range f.PayloadId {
			if len(i) != 8 {
				err = ssz.ErrBytesLength
				return
			}
			hh.PutBytes(i)
		}

		numItems := uint64(len(f.PayloadId))
		hh.MerkleizeWithMixin(subIndx, numItems, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the PayloadAttributesV3SSZ object
func (p *PayloadAttributesV3SSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(p)
}

// MarshalSSZTo ssz marshals the PayloadAttributesV3SSZ object to a target array
func (p *PayloadAttributesV3SSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(96)

	// Field (0) 'Timestamp'
	dst = ssz.MarshalUint64(dst, p.Timestamp)

	// Field (1) 'PrevRandao'
	dst = append(dst, p.PrevRandao[:]...)

	// Field (2) 'SuggestedFeeRecipient'
	dst = append(dst, p.SuggestedFeeRecipient[:]...)

	// Offset (3) 'Withdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.Withdrawals) * 44

	// Field (4) 'ParentBeaconBlockRoot'
	dst = append(dst, p.ParentBeaconBlockRoot[:]...)

	// Field (3) 'Withdrawals'
	if size := len(p.Withdrawals); size > 16 {
		err = ssz.ErrListTooBigFn("--.Withdrawals", size, 16)
		return
	}
	for ii := 0; ii < len(p.Withdrawals); ii++ {
		if dst, err = p.Withdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the PayloadAttributesV3SSZ object
func (p *PayloadAttributesV3SSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 96 {
		return ssz.ErrSize
	}

	tail := buf
	var o3 uint64

	// Field (0) 'Timestamp'
	p.Timestamp = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'PrevRandao'
	copy(p.PrevRandao[:], buf[8:40])

	// Field (2) 'SuggestedFeeRecipient'
	copy(p.SuggestedFeeRecipient[:], buf[40:60])

	// Offset (3) 'Withdrawals'
	if o3 = ssz.ReadOffset(buf[60:64]); o3 > size {
		return ssz.ErrOffset
	}

	if o3 != 96 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (4) 'ParentBeaconBlockRoot'
	copy(p.ParentBeaconBlockRoot[:], buf[64:96])

	// Field (3) 'Withdrawals'
	{
		buf = tail[o3:]
		num, err := ssz.DivideInt2(len(buf), 44, 16)
		if err != nil {
			return err
		}
		p.Withdrawals = make([]*WithdrawalSSZ, num)
		for ii := 0; ii < num; ii++ {
			if p.Withdrawals[ii] == nil {
				p.Withdrawals[ii] = new(WithdrawalSSZ)
			}
			if err = p.Withdrawals[ii].UnmarshalSSZ(buf[ii*44 : (ii+1)*44]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the PayloadAttributesV3SSZ object
func (p *PayloadAttributesV3SSZ) SizeSSZ() (size int) {
	size = 96

	// Field (3) 'Withdrawals'
	size += len(p.Withdrawals) * 44

	return
}

// HashTreeRoot ssz hashes the PayloadAttributesV3SSZ object
func (p *PayloadAttributesV3SSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(p)
}

// HashTreeRootWith ssz hashes the PayloadAttributesV3SSZ object with a hasher
func (p *PayloadAttributesV3SSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Timestamp'
	hh.PutUint64(p.Timestamp)

	// Field (1) 'PrevRandao'
	hh.PutBytes(p.PrevRandao[:])

	// Field (2) 'SuggestedFeeRecipient'
	hh.PutBytes(p.SuggestedFeeRecipient[:])

	// Field (3) 'Withdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(p.Withdrawals))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range p.Withdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	// Field (4) 'ParentBeaconBlockRoot'
	hh.PutBytes(p.ParentBeaconBlockRoot[:])

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the WithdrawalSSZ object
func (w *WithdrawalSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(w)
}

// MarshalSSZTo ssz marshals the WithdrawalSSZ object to a target array
func (w *WithdrawalSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Index'
	dst = ssz.MarshalUint64(dst, w.Index)

	// Field (1) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, w.ValidatorIndex)

	// Field (2) 'Address'
	dst = append(dst, w.Address[:]...)

	// Field (3) 'Amount'
	dst = ssz.MarshalUint64(dst, w.Amount)

	return
}

// UnmarshalSSZ ssz unmarshals the WithdrawalSSZ object
func (w *WithdrawalSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 44 {
		return ssz.ErrSize
	}

	// Field (0) 'Index'
	w.Index = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ValidatorIndex'
	w.ValidatorIndex = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'Address'
	copy(w.Address[:], buf[16:36])

	// Field (3) 'Amount'
	w.Amount = ssz.UnmarshallUint64(buf[36:44])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the WithdrawalSSZ object
func (w *WithdrawalSSZ) SizeSSZ() (size int) {
	size = 44
	return
}

// HashTreeRoot ssz hashes the WithdrawalSSZ object
func (w *WithdrawalSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(w)
}

// HashTreeRootWith ssz hashes the WithdrawalSSZ object with a hasher
func (w *WithdrawalSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Index'
	hh.PutUint64(w.Index)

	// Field (1) 'ValidatorIndex'
	hh.PutUint64(w.ValidatorIndex)

	// Field (2) 'Address'
	hh.PutBytes(w.Address[:])

	// Field (3) 'Amount'
	hh.PutUint64(w.Amount)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ForkchoiceUpdatedV3RequestSSZ object
func (f *ForkchoiceUpdatedV3RequestSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(f)
}

// MarshalSSZTo ssz marshals the ForkchoiceUpdatedV3RequestSSZ object to a target array
func (f *ForkchoiceUpdatedV3RequestSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(100)

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(ForkchoiceState)
	}
	if dst, err = f.ForkchoiceState.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'PayloadAttributes'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		offset += 4
		offset += f.PayloadAttributes[ii].SizeSSZ()
	}

	// Field (1) 'PayloadAttributes'
	if size := len(f.PayloadAttributes); size > 1 {
		err = ssz.ErrListTooBigFn("--.PayloadAttributes", size, 1)
		return
	}
	{
		offset = 4 * len(f.PayloadAttributes)
		for ii := 0; ii < len(f.PayloadAttributes); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += f.PayloadAttributes[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		if dst, err = f.PayloadAttributes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ForkchoiceUpdatedV3RequestSSZ object
func (f *ForkchoiceUpdatedV3RequestSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'ForkchoiceState'
	if f.ForkchoiceState == nil {
		f.ForkchoiceState = new(ForkchoiceState)
	}
	if err = f.ForkchoiceState.UnmarshalSSZ(buf[0:96]); err != nil {
		return err
	}

	// Offset (1) 'PayloadAttributes'
	if o1 = ssz.ReadOffset(buf[96:100]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 100 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'PayloadAttributes'
	{
		buf = tail[o1:]
		num, err := ssz.DecodeDynamicLength(buf, 1)
		if err != nil {
			return err
		}
		f.PayloadAttributes = make([]*PayloadAttributesV3SSZ, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if f.PayloadAttributes[indx] == nil {
				f.PayloadAttributes[indx] = new(PayloadAttributesV3SSZ)
			}
			if err = f.PayloadAttributes[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ForkchoiceUpdatedV3RequestSSZ object
func (f *ForkchoiceUpdatedV3RequestSSZ) SizeSSZ() (size int) {
	size = 100

	// Field (1) 'PayloadAttributes'
	for ii := 0; ii < len(f.PayloadAttributes); ii++ {
		size += 4
		size += f.PayloadAttributes[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ForkchoiceUpdatedV3RequestSSZ object
func (f *ForkchoiceUpdatedV3RequestSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(f)
}

// HashTreeRootWith ssz hashes the ForkchoiceUpdatedV3RequestSSZ object with a hasher
func (f *ForkchoiceUpdatedV3RequestSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ForkchoiceState'
	if err = f.ForkchoiceState.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'PayloadAttributes'
	{
		subIndx := hh.Index()
		num := uint64(len(f.PayloadAttributes))
		if num > 1 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range f.PayloadAttributes {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the GetBlobsRequestSSZ object
func (g *GetBlobsRequestSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(g)
}

// MarshalSSZTo ssz marshals the GetBlobsRequestSSZ object to a target array
func (g *GetBlobsRequestSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'VersionedHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(g.VersionedHashes) * 32

	// Field (0) 'VersionedHashes'
	if size := len(g.VersionedHashes); size > 4096 {
		err = ssz.ErrListTooBigFn("--.VersionedHashes", size, 4096)
		return
	}
	for ii := 0; ii < len(g.VersionedHashes); ii++ {
		if size := len(g.VersionedHashes[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("--.VersionedHashes[ii]", size, 32)
			return
		}
		dst = append(dst, g.VersionedHashes[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the GetBlobsRequestSSZ object
func (g *GetBlobsRequestSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'VersionedHashes'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'VersionedHashes'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 32, 4096)
		if err != nil {
			return err
		}
		g.VersionedHashes = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(g.VersionedHashes[ii]) == 0 {
				g.VersionedHashes[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			g.VersionedHashes[ii] = append(g.VersionedHashes[ii], buf[ii*32:(ii+1)*32]...)
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the GetBlobsRequestSSZ object
func (g *GetBlobsRequestSSZ) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'VersionedHashes'
	size += len(g.VersionedHashes) * 32

	return
}

// HashTreeRoot ssz hashes the GetBlobsRequestSSZ object
func (g *GetBlobsRequestSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(g)
}

// HashTreeRootWith ssz hashes the GetBlobsRequestSSZ object with a hasher
func (g *GetBlobsRequestSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'VersionedHashes'
	{
		if size := len(g.VersionedHashes); size > 4096 {
			err = ssz.ErrListTooBigFn("--.VersionedHashes", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range g.VersionedHashes {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}

		numItems := uint64(len(g.VersionedHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExchangeCapabilitiesSSZ object
func (e *ExchangeCapabilitiesSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExchangeCapabilitiesSSZ object to a target array
func (e *ExchangeCapabilitiesSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Capabilities'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Capabilities); ii++ {
		offset += 4
		offset += len(e.Capabilities[ii])
	}

	// Field (0) 'Capabilities'
	if size := len(e.Capabilities); size > 128 {
		err = ssz.ErrListTooBigFn("--.Capabilities", size, 128)
		return
	}
	{
		offset = 4 * len(e.Capabilities)
		for ii := 0; ii < len(e.Capabilities); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(e.Capabilities[ii])
		}
	}
	for ii := 0; ii < len(e.Capabilities); ii++ {
		if size := len(e.Capabilities[ii]); size > 64 {
			err = ssz.ErrBytesLengthFn("--.Capabilities[ii]", size, 64)
			return
		}
		dst = append(dst, e.Capabilities[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExchangeCapabilitiesSSZ object
func (e *ExchangeCapabilitiesSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Capabilities'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Capabilities'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 128)
		if err != nil {
			return err
		}
		e.Capabilities = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 64 {
				return ssz.ErrBytesLength
			}
			if cap(e.Capabilities[indx]) == 0 {
				e.Capabilities[indx] = make([]byte, 0, len(buf))
			}
			e.Capabilities[indx] = append(e.Capabilities[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExchangeCapabilitiesSSZ object
func (e *ExchangeCapabilitiesSSZ) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Capabilities'
	for ii := 0; ii < len(e.Capabilities); ii++ {
		size += 4
		size += len(e.Capabilities[ii])
	}

	return
}

// HashTreeRoot ssz hashes the ExchangeCapabilitiesSSZ object
func (e *ExchangeCapabilitiesSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExchangeCapabilitiesSSZ object with a hasher
func (e *ExchangeCapabilitiesSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Capabilities'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Capabilities))
		if num > 128 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Capabilities {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 64 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (64+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 128)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ClientVersionV1SSZ object
func (c *ClientVersionV1SSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the ClientVersionV1SSZ object to a target array
func (c *ClientVersionV1SSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Offset (0) 'Code'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(c.Code)

	// Offset (1) 'Name'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(c.Name)

	// Offset (2) 'Version'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(c.Version)

	// Field (3) 'Commit'
	dst = append(dst, c.Commit[:]...)

	// Field (0) 'Code'
	if size := len(c.Code); size > 8 {
		err = ssz.ErrBytesLengthFn("--.Code", size, 8)
		return
	}
	dst = append(dst, c.Code...)

	// Field (1) 'Name'
	if size := len(c.Name); size > 64 {
		err = ssz.ErrBytesLengthFn("--.Name", size, 64)
		return
	}
	dst = append(dst, c.Name...)

	// Field (2) 'Version'
	if size := len(c.Version); size > 64 {
		err = ssz.ErrBytesLengthFn("--.Version", size, 64)
		return
	}
	dst = append(dst, c.Version...)

	return
}

// UnmarshalSSZ ssz unmarshals the ClientVersionV1SSZ object
func (c *ClientVersionV1SSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1, o2 uint64

	// Offset (0) 'Code'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Name'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Offset (2) 'Version'
	if o2 = ssz.ReadOffset(buf[8:12]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (3) 'Commit'
	copy(c.Commit[:], buf[12:16])

	// Field (0) 'Code'
	{
		buf = tail[o0:o1]
		if len(buf) > 8 {
			return ssz.ErrBytesLength
		}
		if cap(c.Code) == 0 {
			c.Code = make([]byte, 0, len(buf))
		}
		c.Code = append(c.Code, buf...)
	}

	// Field (1) 'Name'
	{
		buf = tail[o1:o2]
		if len(buf) > 64 {
			return ssz.ErrBytesLength
		}
		if cap(c.Name) == 0 {
			c.Name = make([]byte, 0, len(buf))
		}
		c.Name = append(c.Name, buf...)
	}

	// Field (2) 'Version'
	{
		buf = tail[o2:]
		if len(buf) > 64 {
			return ssz.ErrBytesLength
		}
		if cap(c.Version) == 0 {
			c.Version = make([]byte, 0, len(buf))
		}
		c.Version = append(c.Version, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ClientVersionV1SSZ object
func (c *ClientVersionV1SSZ) SizeSSZ() (size int) {
	size = 16

	// Field (0) 'Code'
	size += len(c.Code)

	// Field (1) 'Name'
	size += len(c.Name)

	// Field (2) 'Version'
	size += len(c.Version)

	return
}

// HashTreeRoot ssz hashes the ClientVersionV1SSZ object
func (c *ClientVersionV1SSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the ClientVersionV1SSZ object with a hasher
func (c *ClientVersionV1SSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Code'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(c.Code))
		if byteLen > 8 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(c.Code)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (8+31)/32)
	}

	// Field (1) 'Name'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(c.Name))
		if byteLen > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(c.Name)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (64+31)/32)
	}

	// Field (2) 'Version'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(c.Version))
		if byteLen > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(c.Version)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (64+31)/32)
	}

	// Field (3) 'Commit'
	hh.PutBytes(c.Commit[:])

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ClientVersionResponseSSZ object
func (c *ClientVersionResponseSSZ) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the ClientVersionResponseSSZ object to a target array
func (c *ClientVersionResponseSSZ) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Versions'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(c.Versions); ii++ {
		offset += 4
		offset += c.Versions[ii].SizeSSZ()
	}

	// Field (0) 'Versions'
	if size := len(c.Versions); size > 16 {
		err = ssz.ErrListTooBigFn("--.Versions", size, 16)
		return
	}
	{
		offset = 4 * len(c.Versions)
		for ii := 0; ii < len(c.Versions); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += c.Versions[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(c.Versions); ii++ {
		if dst, err = c.Versions[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ClientVersionResponseSSZ object
func (c *ClientVersionResponseSSZ) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Versions'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Versions'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 16)
		if err != nil {
			return err
		}
		c.Versions = make([]*ClientVersionV1SSZ, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if c.Versions[indx] == nil {
				c.Versions[indx] = new(ClientVersionV1SSZ)
			}
			if err = c.Versions[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ClientVersionResponseSSZ object
func (c *ClientVersionResponseSSZ) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Versions'
	for ii := 0; ii < len(c.Versions); ii++ {
		size += 4
		size += c.Versions[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ClientVersionResponseSSZ object
func (c *ClientVersionResponseSSZ) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the ClientVersionResponseSSZ object with a hasher
func (c *ClientVersionResponseSSZ) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Versions'
	{
		subIndx := hh.Index()
		num := uint64(len(c.Versions))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range c.Versions {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	hh.Merkleize(indx)
	return
}
